### ISSUE TITLE
Cleanup the distributed package

### ISSUE THREAD

**Issue by adiroiban** [chevah/python-package#159]
For python-package I think that the final "packaging script" should be updated to do the following

* remove /man directory
* move /include into lib/includ
* move /pkgconifg into the existing /lib/pkgconfig

**Comment by dumol** [comment]
Fixed as a drive-by in https://github.com/chevah/python-package/pull/158/commits/232fc26c926d4b5c8df6e3c8f8924c5a31cf547a.
