### ISSUE TITLE
Have python compiled and tested on Fedora 25.

### ISSUE THREAD

**Issue by dispera** [chevah/python-package#60]
I have been trying to compile python-package on Fedora 25 (released last week).

So far I had to install this dependencies:
automake
libtool
textinfo (for makeinfo)
zlib-devel (for zlib not found errors, although zlib was installed)
openssl-devel (cannot import HTTPSHandler error)
*At this point I also reinstalled python to take the openssl changes as per what I read.

Compiling again right now, let's see how it goes.

**Comment by dispera** [comment]
Success! It compiled after last changes :)

![screen shot 2016-11-29 at 7 56 02 am](https://cloud.githubusercontent.com/assets/21148841/20705239/52c74094-b609-11e6-8df6-e4b200ee0d5b.png)

**Comment by adiroiban** [comment]
Great work..

but right now Fedora 25 is of low priority for us... we target  RHEL and Centos as we don't have customers using Fedore... hence nobody is paying us to work for Fedora

I will close this ticket as we have many other tasks to work on and for which the customers are waiting for us
